### ISSUE TITLE
Any plan for a CentOS 7 rpm repo?

### ISSUE THREAD

**Issue by gioppoluca** [kermitfr/restmco#6]
Is there any plan on releasing a version 7 repo?
Thanks

**Comment by mmornati** [comment]
Hello. I built the rpm for Centos7... 
http://repo.mornati.net/kermit-restmco-2.2-1.el7.centos.noarch.rpm

... but to be honest should be better to improve some things to make 100% compatibility with Centos7.
For exemple the init.d script will work better as systemd .service file...

I let you to test the RPM (ruby is available in Centos7 official repositories).

Let me know.
Marco
